apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-testing-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: Pod
metadata:
  name: ceph-test-pod
spec:
  restartPolicy: Never
  containers:
  - image: centos:7
    name: test
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
      - mountPath: /var/data
        name: test
  volumes:
  - name: test
    persistentVolumeClaim:
      claimName: ceph-testing-pvc
