apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
  - image: ubuntu
    name: test-container
    command: ["tail", "-f", "/dev/null"]
    volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/podwatcher
        name: token
  volumes:
   - name: token
     secret:
       secretName: pod-watcher-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-watcher
  namespace: default
secrets:
- name: pod-watcher-token
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: f3-pod-watcher
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cnsbench-binding
subjects:
  - kind: ServiceAccount
    name: pod-watcher
    namespace: default
roleRef:
  kind: ClusterRole
  name: f3-pod-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: pod-watcher-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: pod-watcher
type: kubernetes.io/service-account-token
