apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nfs-pvc
  namespace: openwhisk
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: all-nfs
