apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: owdev-openwhisk
    app.kubernetes.io/managed-by: Helm
    chart: openwhisk-1.0.0
    heritage: Helm
    release: owdev
  name: nfs-nfs-pvc
  namespace: openwhisk
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: all-nfs