kind: Deployment
apiVersion: apps/v1
metadata:
  name: global-nfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: global-nfs-provisioner
  template:
    metadata:
      labels:
        app: global-nfs-provisioner
    spec:
      serviceAccountName: global-nfs-provisioner
      containers:
        - name: global-nfs-provisioner
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: example/nfs
            - name: NFS_SERVER
              value: 10.10.1.1
            - name: NFS_PATH
              value: /storage/nfs
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.10.1.1
            path: /storage/nfs
