apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: all-nfs
  #annotations:
  #  storageclass.kubernetes.io/is-default-class: "true"
provisioner: example/nfs
allowVolumeExpansion: true
parameters:
  archiveOnDelete: "false"
