---
# This YAML file contains driver-registrar & csi driver nodeplugin API objects
# that are necessary to run CSI nodeplugin for f3
kind: Pod
apiVersion: v1
metadata:
  name: csi-f3-node
  namespace: default
spec:
  hostNetwork: true  # original f3 connection would be broken without hostNetwork setting
  dnsPolicy: ClusterFirstWithHostNet
  nodeName: kubes1
  containers:
    - name: liveness-probe
      image: k8s.gcr.io/sig-storage/livenessprobe:v2.1.0
      args:
        - --csi-address=/csi/csi.sock
        - --probe-timeout=3s
        - --health-port=29653
        - --v=2
      volumeMounts:
        - name: socket-dir
          mountPath: /csi
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 10m
          memory: 20Mi
    - name: node-driver-registrar
      image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.0.1
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "rm -rf /registration/csi-f3plugin /registration/csi-f3plugin-reg.sock"]
      args:
        - --v=2
        - --csi-address=/csi/csi.sock
        - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-f3plugin/csi.sock
      env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: registration-dir
          mountPath: /registration
    - name: f3
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
        allowPrivilegeEscalation: true
      #image: mcr.microsoft.com/k8s/csi/f3-csi:latest
      image: kubes1:5000/f3/f3-csi:0.0.4
      imagePullPolicy: Always
      command: ["tail", "-f", "/dev/null"]
      #args:
      #  - "-v=5"
      #  - "--nodeid=$(NODE_ID)"
      #  - "--endpoint=$(CSI_ENDPOINT)"
      env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
      ports:
        - containerPort: 29653
          name: healthz
          protocol: TCP
      livenessProbe:
        failureThreshold: 5
        httpGet:
          path: /healthz
          port: healthz
        initialDelaySeconds: 30
        timeoutSeconds: 10
        periodSeconds: 30
      volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: pods-mount-dir
          mountPath: /var/lib/kubelet/pods
          mountPropagation: "Bidirectional"
        - name: mnt-dir
          mountPath: /hostmnt/
  volumes:
    - name: socket-dir
      hostPath:
        path: /var/lib/kubelet/plugins/csi-f3plugin
        type: DirectoryOrCreate
    - name: pods-mount-dir
      hostPath:
        path: /var/lib/kubelet/pods
        type: Directory
    - hostPath:
        path: /var/lib/kubelet/plugins_registry
        type: Directory
      name: registration-dir
    - hostPath:
        path: /mnt/
        type: Directory
      name: mnt-dir
